/*
D&D 5e API

Testing SubclassesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_openapi_SubclassesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SubclassesAPIService ApiSubclassesIndexFeaturesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var index string

		resp, httpRes, err := apiClient.SubclassesAPI.ApiSubclassesIndexFeaturesGet(context.Background(), index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubclassesAPIService ApiSubclassesIndexGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var index string

		resp, httpRes, err := apiClient.SubclassesAPI.ApiSubclassesIndexGet(context.Background(), index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubclassesAPIService ApiSubclassesIndexLevelsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var index string

		resp, httpRes, err := apiClient.SubclassesAPI.ApiSubclassesIndexLevelsGet(context.Background(), index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubclassesAPIService ApiSubclassesIndexLevelsSubclassLevelFeaturesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var index string
		var subclassLevel int32

		resp, httpRes, err := apiClient.SubclassesAPI.ApiSubclassesIndexLevelsSubclassLevelFeaturesGet(context.Background(), index, subclassLevel).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SubclassesAPIService ApiSubclassesIndexLevelsSubclassLevelGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var index string
		var subclassLevel int32

		resp, httpRes, err := apiClient.SubclassesAPI.ApiSubclassesIndexLevelsSubclassLevelGet(context.Background(), index, subclassLevel).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
